apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}-vs"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Release.Name }}-gw
  hosts:
    {{- range .Values.ingress.hosts  }}
      - {{ .host }}
    {{- end }}
  http:
    - route:
        - destination:
            host: {{ template "github-exporter.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
