# Default values for github-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

serviceAccount:
  name: github-exporter

securityContext:
  runAsNonRoot: true
  runAsUser: 1024

serviceAccount:
  name: github-exporter

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

host: github-exporter.monitoring.svc.cluster.local
cmsHost: https://cms.dev.xrspace.io
