---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name:
    "{ .Release.Name  }": -gw
  namespace:
    "{ .Release.Namespace }": null
spec:
  selector:
    istio: gateway
  servers:
    - hosts:
        - "{ .Values.host }": null
      port:
        name: http
        number: 80
        protocol: HTTP
