apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
    - {{ .Release.Name }}-gw
  hosts:
    - {{ .Values.host }}
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}-svc
            port:
              number: {{ .Values.service.port }}
      corsPolicy:
        allowCredentials: true
        allowHeaders:
          - authorization
          - content-type
        allowMethods:
          - POST
          - GET
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        allowOrigins:
          - exact: {{ .Values.cmsHost }}
        exposeHeaders:
          - content-length
        maxAge: 24h
