name: Package MONITOR helm-chart OCI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      TARGET_BRANCH:
        description: "The target branch"
        default: ""
        type: string

env:
  ECR_REPOSITORY: tp-five/one-monitor/github-exporter-poc

jobs:
  package_helm_chart:
    name: Package github-exporter OCI
    runs-on: ["self-hosted", "g4dn-xlarge"]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.TARGET_BRANCH || '' }}

      # Setup
      # ==================================================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - uses: ./one-utility/actions/ecr_image_tag
        id: ecr_image_tag
        with:
          ecr_repository: ${{ env.ECR_REPOSITORY }}
      - name: Preparing helm-charts for OCI
        if: ${{ steps.ecr_image_tag.outputs.already_exists == 'false' }}
        env:
          IMAGE_TAG: ${{ steps.ecr_image_tag.outputs.image_tag }}
          ECR_REGISTRY: ${{ steps.ecr_image_tag.outputs.ecr_registry }}
        run: |
          pushd one-monitor || exit 1
          helm package github-exporter-poc/
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" > ecr_tag.txt
          helm push github-exporter-4.1.0.tgz oci://511635964514.dkr.ecr.ap-southeast-1.amazonaws.com/
          popd
